# Generated by Django 5.0.7 on 2024-08-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_daftar_wali_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daftar_Sanksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poin', models.CharField(max_length=10)),
                ('sanksi', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Daftar Sanksi',
            },
        ),
    ]
